# Site settings
title: HSIAO CHUNYI
email: hsiaocy@fuji.waseda.jp
description: > # "Hello world!" # this means to ignore newlines until "baseurl:" Hello world.
  Hellooooooooooooo!


# Link settings
baseurl: "" # the suã„‹bpath of your site, e.g. /blog
url: "https://hsiaocy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Social settings
social_sites:
  #twitter: jekyllrb
  github:  hsiaocy
  #dribbble: jekyll
  facebook: hsiaochunyi
  #flickr: jekyll
  #instagram: hsiaochunyi
  linkedin: chunyi-hsiao-21488b122
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

rss: rss

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Kramdown settings
kramdown:
  input: GFM


# Highlighter settings
highlighter: rouge

# Disqus
disqus:
  shortname: hsiaocy-github-io-1

# Publish future
future: true

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: hsiaocy
  email: hsiaocy@fuji.waseda.jp
  bio: yolo
  avatar: bio-IMG_5343.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

